# ECON8080 Homework 1

**Name**: Ali Furkan Kalay

**ID:** 45625365

In [1]:
import numpy as np

## Question 1

In [2]:
n = 10
x = np.random.rand()      # Initializing random x value
a = np.random.randn(n)    # Initializing random a in R^n

def horner(x,a):
    p = 0.0
    for i in reversed(range(0,len(a))):        # In order to iterate from n-1 to 0 I reversed() the range(0,n)
        p = a[i] + p*x           #
        print(i)
    return p 

In [3]:
horner(x,a)

9
8
7
6
5
4
3
2
1
0


0.33465191122388954

## Question 2

I use *string*.`isnumeric()` function to check if input contains any non-digit character. `isnumeric()` function returns FALSE if input is negative. Therefore it is not necessary to check if it is negative. So any non-positive number or nonnumeric value returns false.

In [4]:
number = input('Enter a number: ')
if number.isnumeric():
    if int(number)%2 == 0:
        print('It is a positive even number.')
    else:
        print('It is a positive odd number.')
else:
    print('It is either negative or non-integer number.')

Enter a number: 5
It is a positive odd number.


## Question 3

If the input string cannot be converted into a integer or float then it implies string is not a number. The first control is done in the previous question. For the second, we will check if string can be converted into a `float` object. Instead of `if` statement I use exception handling method `try`. If `float()` gives any error then string is not a number. 

In [5]:
number = input('Enter a number: ')

if number.isnumeric():
    if int(number)%2 == 0:
        print('It is a positive even number.')
    else:
        print('It is a positive odd number.')
else:
    try:
        float(number)
        print('It is either negative or non-integer number.')
    except:
        print('It is not a number.')

Enter a number: O
It is not a number.


## Question 4

In [6]:
def converge(x, tolerance=1e-8):     # I assigned a default value for tolerance. 
    print(x)
    while True:
        compare = x                  # At the beginning of the loops I assign x_n to a variable
        x = 1 + 1/x                  # This is x_(n+1)
        print(x)                     # Printing x_(n+1)
        if (np.absolute(x-compare)/compare<tolerance):         #Tolerance condition: |x_(n+1)-x_n|<tolerance
            break          # After satisfying the tolerance condition the loop will break/stop. 

In [7]:
converge(200)

200
1.005
1.9950248756218907
1.5012468827930174
1.6661129568106312
1.6001994017946162
1.6249221183800624
1.6154141104294477
1.6190363161642536
1.6176513707667497
1.618180170382454
1.6179781573788854
1.6180553151718646
1.618025842888927
1.6180371002075813
1.6180328002810986
1.6180344427049138
1.6180338153545555
1.6180340549810281
1.6180339634518541
1.6180339984128866
1.6180339850589605


## Question 5

I used numpy's `polymul` function for polynomial multiplication. First I define a recursive function that generates the polynom coefficients for $ T_n(x) $. Since $ T_0 $ and $ T_1 $ are initially given we define it under a if clause. 

In [8]:
def T(n):
    if n==0:
        return [1]
    elif n ==1:
        return [1,0]
    else:
        return (np.polymul(np.poly1d([2,0]),np.poly1d(T(n-1))) - np.poly1d(T(n-2))).coefficients 

The code inside the last return function stands for the $$ T_{n+1} = 2x T_n(x) - T_{n-1}(x) $$ 

Also note that `np.poly1d([2,0]` stands for the $ 2x $. The order of coefficients is opposite in numpy library so we will reverse it later. e.g. $ T_5(x) $ coefficients starts from $x^5$:

In [9]:
T(5)

array([ 16,   0, -20,   0,   5,   0])

Now we will define the function that generates `Tmat` matrix. I use `numpy.pad()` function to fill empty columns. 

In [10]:
def Tmat_gen(N):
    matrix = []
    for i in range(N+1):
        matrix.append(np.pad(T(i)[::-1], pad_width=(0,N+1-len(T(i))),mode = 'constant',constant_values=0))
    return np.array(matrix)

- I generate an empty list `matrix = []` to append each row. 
- Since we require $(N+1)\times (N+1)$ matrix we iterate `range(N+1)`.
- `T(i)[::-1]` is reversing the order of coefficients. 
- `np.pad()` function fill 0s for empty columns. For each $T_n$ we have different pad width: `pad_width=(0,N+1-len(T(i)))`.
- We append coefficient rows from $ T_0$ to $T_n$ to `matrix` variable and return it as an numpy array. 

For $N = 5$:

In [11]:
Tmat = Tmat_gen(5)

In [16]:
print(type(Tmat))

<class 'numpy.ndarray'>


In [15]:
print(Tmat)

[[  1   0   0   0   0   0]
 [  0   1   0   0   0   0]
 [ -1   0   2   0   0   0]
 [  0  -3   0   4   0   0]
 [  1   0  -8   0   8   0]
 [  0   5   0 -20   0  16]]


`Tmat[i,j]` stores the coefficient of $x^j$ in $T_i(x)$ for $i,j\in\{0,1,...5\}$. e.g.

In [13]:
Tmat[3,1]

-3